# Generated by Django 4.2.7 on 2023-11-11 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipes",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="recipe_name",
            field=models.CharField(max_length=500),
        ),
    ]
