# Generated by Django 4.2.7 on 2023-11-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0002_recipes_timestamp_recipes_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredient_name", models.CharField(max_length=500)),
                ("stock_quantity", models.IntegerField(default=0)),
                ("unit", models.CharField(max_length=100)),
            ],
        ),
    ]
