# Generated by Django 4.2.7 on 2023-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0004_recipes_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="ingredients",
            field=models.ManyToManyField(
                through="landing_pages.Recipes_Ingredients",
                to="landing_pages.ingredients",
            ),
        ),
    ]
