# Generated by Django 4.2.7 on 2023-11-13 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0005_recipes_ingredients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="ingredients",
        ),
    ]
