# Generated by Django 4.2.7 on 2023-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0006_remove_recipes_ingredients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=500)),
                ("machine_type", models.CharField(max_length=500)),
            ],
        ),
    ]
