# Generated by Django 4.2.7 on 2023-11-13 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0007_machine"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Machine",
            new_name="Machines",
        ),
    ]
