# Generated by Django 4.2.7 on 2023-11-13 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0008_rename_machine_machines"),
    ]

    operations = [
        migrations.AddField(
            model_name="machines",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="machines",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
