# Generated by Django 4.2.7 on 2023-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0010_delete_machines"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("machine_name", models.CharField(max_length=500)),
                ("machine_type", models.CharField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
