# Generated by Django 4.2.7 on 2023-11-14 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0011_machines"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="landing_pages.recipes",
                    ),
                ),
            ],
        ),
    ]
