# Generated by Django 4.2.7 on 2023-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0013_recipe_machines"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="machine",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=models.SET(None),
                to="landing_pages.machines",
            ),
        ),
        migrations.AddField(
            model_name="recipes",
            name="machine_duration",
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Recipe_Machines",
        ),
    ]
