# Generated by Django 4.2.7 on 2023-11-19 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0014_recipes_machine_recipes_machine_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipes",
            name="description",
        ),
    ]
