# Generated by Django 4.2.7 on 2023-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0015_remove_recipes_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="machines",
            name="status",
            field=models.CharField(
                choices=[("In use", "In use"), ("Free", "Free")],
                default="Free",
                max_length=10,
            ),
        ),
    ]
