# Generated by Django 4.2.7 on 2023-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0016_machines_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="machines",
            name="remaining_time",
            field=models.FloatField(default=0.0),
        ),
    ]
