# Generated by Django 4.2.7 on 2023-12-05 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landing_pages", "0021_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
